Align with IntelliJ
liancheng/scalafix-organize-imports pull request #146
Opened 2020-12-28 17:25 UTC by sideeffffect

* `groupedImports = Merge` to prevent conflict with IntelliJ
 * `expandRelative = true` to make converging with IntelliJ's _Optimize imports_ faster

Maybe there are other changes necessary to match IntelliJ 100%, but from my experience over many months, using
```hocon
OrganizeImports {
  expandRelative = true
  groupedImports = Merge
  groups = [
    "*"
    "re:(javax?|scala)\\."
  ]
}
```
doesn't cause any conflicts between IntelliJ and `scalafix-organize-imports`.

2020-12-28 18:40 UTC, liancheng requested changes

2020-12-28 18:40 UTC, liancheng commented on output/src/main/scala/fix/RelativeImports.scala
> -
This change violates the original motivation of the test. It meant to test whether relative imports are grouped in a separate order-preserving group, but now they are expanded.

To avoid such issues, let's not change the output files but update the `OrganizeImports` configurations in all the input files to reflect the new default configuration values.

2020-12-28 18:48 UTC, liancheng commented
Thanks, @sideeffffect. I left a comment about the changes in the tests, otherwise LGTM.

I'm afraid we won't be able to be 100% IntelliJ compatible because `OrganizeImports` values correctness more than conciseness because it is supposed to be used in a batch manner. The default IntelliJ configuration values conciseness more even though sometimes it may produce wrong results. For example:

> Class count to use import with '_': 5

The above configuration is equivalent to `OrganizeImports.coalesceToWildcardImportThreshold = 5`, which is not recommended and may result in compilation errors in corner cases (see [here](https://github.com/liancheng/scalafix-organize-imports/tree/869e4279bf3201d0bd1e573b683b8e1e6eb659b2#coalesce)).

Changes proposed in this PR are safe, though.

2020-12-28 18:51 UTC, liancheng commented
Oh, actually, another issue: defaulting `expandRelative` to `true` may produce unused imports that cannot be removed even if you set `removeUnused` to `true`. See [here](https://github.com/liancheng/scalafix-organize-imports/tree/869e4279bf3201d0bd1e573b683b8e1e6eb659b2#expand-relative). This means that if you set both `expandRelative` and `removeUnused` to `true`, then the output may not be idempotent unless you run `OrganizeImports` at least twice. It was the biggest reason why I didn't enable it by default.

I'm not quite sure whether it's a good idea to enable it by default.

2020-12-28 19:21 UTC, liancheng commented
I'm thinking maybe we can add a `basedOnStyle` option to provide different sets of default configurations. Say:

```hocon
OrganizeImports.basedOnStyle = IntelliJ_2020_3
```

implies:

```hocon
OrganizeImports {
  coalesceToWildcardImportThreshold = 5
  groups = [
    "*",
    "re:(javax?|scala)\\."
  ]
  groupedImports = Merge
}
```

Users can still override individual options.

2021-01-03 21:34 UTC, sideeffffect commented
I've changed default `expandRelative = false`. I think this is good to go into master and then release. Then we can wait for feedback how it works in practice :wink: 

While in the future it may turn out handy to have a `basedOnStyle` setting, I don't think we're there yet. So far I would bet that we can get away without using it, so let's not add it just yet. We'll see how far we can get with just IntelliJ-aligned defaults after this PR is merged and a new `scalafix-organize-imports` version released.

2021-01-12 02:32 UTC, merged

2021-01-12 02:32 UTC, liancheng commented
Thanks and merged!